/**
 * File:  rpi_peripherals.h
 * Author: ymiyamoto
 *
 * Created on Sun Mar 19 03:43:31 2017
 */

#ifndef _RPI_PERIPHERALS_H_
#define _RPI_PERIPHERALS_H_

#include "rpi_lib/rpi_types.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef vuint32_t *rpi_peripheral_addr_t;

#define PHY_PERI_ADDR(addr) ((rpi_peripheral_addr_t)(0x3F000000 + addr))

#define GPIO_BASE (0x200000)
#define GPIO_GPFSEL0 PHY_PERI_ADDR(GPIO_BASE + 0x00)
#define GPIO_GPFSEL1 PHY_PERI_ADDR(GPIO_BASE + 0x04)
#define GPIO_GPFSEL2 PHY_PERI_ADDR(GPIO_BASE + 0x08)
#define GPIO_GPFSEL3 PHY_PERI_ADDR(GPIO_BASE + 0x0C)
#define GPIO_GPFSEL4 PHY_PERI_ADDR(GPIO_BASE + 0x10)
#define GPIO_GPFSEL5 PHY_PERI_ADDR(GPIO_BASE + 0x14)

#define GPIO_GPSET0 PHY_PERI_ADDR(GPIO_BASE + 0x1C)
#define GPIO_GPSET1 PHY_PERI_ADDR(GPIO_BASE + 0x20)
#define GPIO_GPCLR0 PHY_PERI_ADDR(GPIO_BASE + 0x28)
#define GPIO_GPCLR1 PHY_PERI_ADDR(GPIO_BASE + 0x2C)
#define GPIO_GPLEV0 PHY_PERI_ADDR(GPIO_BASE + 0x34)
#define GPIO_GPLEV1 PHY_PERI_ADDR(GPIO_BASE + 0x38)

#define GPIO_GPPUD PHY_PERI_ADDR(GPIO_BASE + 0x94)
#define GPIO_GPPUDCLK0 PHY_PERI_ADDR(GPIO_BASE + 0x98)
#define GPIO_GPPUDCLK1 PHY_PERI_ADDR(GPIO_BASE + 0x9c)

#define SYST_BASE (0x003000)
#define SYST_CLO PHY_PERI_ADDR(SYST_BASE + 0x04)
#define SYST_CHI PHY_PERI_ADDR(SYST_BASE + 0x08)

#define UART0_BASE (0x201000)
#define UART0_DR PHY_PERI_ADDR(UART0_BASE + 0x00)
#define UART0_FR PHY_PERI_ADDR(UART0_BASE + 0x18)
#define UART0_IBRD PHY_PERI_ADDR(UART0_BASE + 0x24)
#define UART0_FBRD PHY_PERI_ADDR(UART0_BASE + 0x28)
#define UART0_LCRH PHY_PERI_ADDR(UART0_BASE + 0x2c)
#define UART0_CR PHY_PERI_ADDR(UART0_BASE + 0x30)

#define BSC1_BASE (0x804000)
#define BSC1_C PHY_PERI_ADDR(BSC1_BASE + 0x00)
#define BSC1_S PHY_PERI_ADDR(BSC1_BASE + 0x04)
#define BSC1_DLEN PHY_PERI_ADDR(BSC1_BASE + 0x08)
#define BSC1_A PHY_PERI_ADDR(BSC1_BASE + 0x0C)
#define BSC1_FIFO PHY_PERI_ADDR(BSC1_BASE + 0x10)
#define BSC1_DIV PHY_PERI_ADDR(BSC1_BASE + 0x14)
#define BSC1_DEL PHY_PERI_ADDR(BSC1_BASE + 0x18)
#define BSC1_CLKT PHY_PERI_ADDR(BSC1_BASE + 0x1C)

#define SPI0_BASE (0x204000)

#define SPI0_CS PHY_PERI_ADDR(SPI0_BASE + 0x00)
#define SPI0_FIFO PHY_PERI_ADDR(SPI0_BASE + 0x04)
#define SPI0_CLK PHY_PERI_ADDR(SPI0_BASE + 0x08)
#define SPI0_DLEN PHY_PERI_ADDR(SPI0_BASE + 0x0C)
#define SPI0_LTOH PHY_PERI_ADDR(SPI0_BASE + 0x10)
#define SPI0_DC PHY_PERI_ADDR(SPI0_BASE + 0x14)

#ifdef __cplusplus
}
#endif

#endif /* _RPI_PERIPHERALS_H_ */
